name: UI tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Обновляем pip до последней версии
          pip install -r requirements.txt  # Устанавливаем зависимости, указанные в requirements.txt
          playwright install --with-deps  # Устанавливаем браузеры для Playwright (если они не установлены)

      - name: Run Playwright tests with pytest and generate Allure results
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses=2

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

  publish-report:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()  # Всегда выполняем, независимо от успеха или неудачи предыдущих шагов
        continue-on-error: true  # Если здесь возникнет ошибка, workflow всё равно продолжит выполнение
        with:
          ref: gh-pages  # Указываем ветку gh-pages для получения отчётов
          path: gh-pages  # Указываем путь для сохранения отчётов

      - name: Generates Allure Report with history
        uses: simple-elf/allure-report-action@v1.7  # Используем готовое решение из GitHub Marketplace для генерации Allure отчёта
        if: always()  # Этот шаг тоже всегда выполняется
        with:
          allure_results: allure-results  # Указываем каталог с результатами тестов
          allure_history: allure-history  # Указываем каталог для истории отчётов Allure

      - name: Deploy report to Github Pages
        if: always()  # Выполняется всегда, независимо от успеха других шагов
        uses: peaceiris/actions-gh-pages@v2  # Используем GitHub Action для публикации отчёта на GitHub Pages
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для аутентификации на GitHub
          PUBLISH_BRANCH: gh-pages  # Указываем, что отчёт будет опубликован в ветке gh-pages
          PUBLISH_DIR: allure-history  # Указываем папку, которая будет опубликована на GitHub Pages